### ISSUE TITLE
module 'oauthlib.oauth1.rfc5849.signature' has no attribute 'signature_base_string'

### ISSUE THREAD

**Issue by xandre31** [jupyterhub/ltiauthenticator#46]
Hi,

I just install litAuthenticator in my conda environment : pip install jupyterhub-ltiauthenticator and configured key and secret for usage with Moodle, but when I connect to jupyterhub URL from Moodle, I got this exception : 

HTTPServerRequest(protocol='http', host='xxxxxxxxxxxxxxxxx', method='POST', uri='/hub/lti/launch', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/ltiauthenticator/__init__.py", line 214, in post
        _ = yield self.login_user()
      File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 655, in login_user
        authenticated = await self.authenticate(data)
      File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/jupyterhub/auth.py", line 383, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/ltiauthenticator/__init__.py", line 150, in authenticate
        args
      File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/ltiauthenticator/__init__.py", line 83, in validate_launch_request
        base_string = signature.signature_base_string(
    **AttributeError: module 'oauthlib.oauth1.rfc5849.signature' has no attribute 'signature_base_string'**

Could you help me to solve it please ?

Thank your for your kind help
Best regards,

**Comment by xandre31** [comment]
Exception is removed when I uninstall oauthlib from pip (pip uninstall oauthlib) and reinstall it from conda (conda install oauthlib)
